### ISSUE TITLE
Error when start game use the version in target folder.

### ISSUE THREAD

**Issue by MyBlueHorizon** [Ayman-Isam/HungerGames#5] opened 2024-02-21 06:05 UTC
[13:52:09 WARN]: [HungerGames] Task #7 for HungerGames v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @726f3b58)
        at me.cantankerousally.hungergames.commands.ChestRefillCommand.onCommand(ChestRefillCommand.java:67) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.handler.GameHandler.startGame(GameHandler.java:202) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.commands.StartGameCommand.lambda$onCommand$0(StartGameCommand.java:87) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:52:39 WARN]: [HungerGames] Task #20 for HungerGames v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @726f3b58)
        at me.cantankerousally.hungergames.commands.SupplyDropCommand.onCommand(SupplyDropCommand.java:49) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.handler.GameHandler$1.run(GameHandler.java:194) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:53:09 WARN]: [HungerGames] Task #20 for HungerGames v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @726f3b58)
        at me.cantankerousally.hungergames.commands.SupplyDropCommand.onCommand(SupplyDropCommand.java:49) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.handler.GameHandler$1.run(GameHandler.java:194) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:53:39 WARN]: [HungerGames] Task #20 for HungerGames v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @726f3b58)
        at me.cantankerousally.hungergames.commands.SupplyDropCommand.onCommand(SupplyDropCommand.java:49) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.handler.GameHandler$1.run(GameHandler.java:194) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:54:09 WARN]: [HungerGames] Task #20 for HungerGames v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @726f3b58)
        at me.cantankerousally.hungergames.commands.SupplyDropCommand.onCommand(SupplyDropCommand.java:49) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.handler.GameHandler$1.run(GameHandler.java:194) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:54:39 WARN]: [HungerGames] Task #20 for HungerGames v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @726f3b58)
        at me.cantankerousally.hungergames.commands.SupplyDropCommand.onCommand(SupplyDropCommand.java:49) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at me.cantankerousally.hungergames.handler.GameHandler$1.run(GameHandler.java:194) ~[HungerGames-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2138]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by MyBlueHorizon** [comment] 2024-02-21 06:07
I want to confirm some translated text how display in game, but the error show even I do not any thing.
I just run /start
And Multi-language support seem can't work.

**Comment by Ayman-Isam** [comment] 2024-02-21 07:17
That's weird since I'm running this on my 1.20.4 paper server and there are no issues like the one you got in the console. I've done a fix that could help with this issue but I can't really replicate it so that's a bit harder. Try this [file](https://drive.google.com/file/d/1pSfK4XB2EcPe_5UK9xnDHeV1i1Mrftlf/view?usp=sharingl) and see if that fixes the issue. Also the plugin works by detecting your Minecraft language and using the correct language file. What language are you using in minecraft. You might also have to disconnect and reconnect for the language changes to take place.

**Comment by MyBlueHorizon** [comment] 2024-02-21 12:13
Could you upload it in other way?
Google Drive is inaccessible for me.
I use original-HungerGames-1.2.5-1.20.4 form Github and switch to Paper.
The same error happened again when the chest need to be filled or supply need to be spawn.
The Multi-language support also can't work. I use zh_CN in game.
![图片](https://github.com/Ayman-Isam/Hunger-Games/assets/20754543/93508751-8f6b-4e6a-8e23-b6368aed50c9)

**Comment by Ayman-Isam** [comment] 2024-02-21 17:08
Have you tried using other languages, for example french france or spain espane? Also do you mind sharing the server console when you run those commands with me? The test branch of the plugin should have the latest version of the plugin, I've just uploaded it.

**Comment by MyBlueHorizon** [comment] 2024-02-22 06:43
The file still is old for 1.20.4.
It doesn't have lang files.
I think it is the problem.
And I switch to 1.20 which has lang files, but all text still in English.
The file in test branch don't have the problem of the error when spawn chest.
Also, I think set up a CI by Github Action is a good idea.

**Comment by MyBlueHorizon** [comment] 2024-02-22 06:58
The france also can't work. Also the message have some problem(Message not found).
![图片](https://github.com/Ayman-Isam/Hunger-Games/assets/20754543/31547eac-8795-427d-95c7-ca25eda9febb)

[14:52:14 INFO]: Master issued server command: /start
[14:52:14 INFO]: The game will start in 20 seconds!
[14:52:19 INFO]: 15 seconds left!
[14:52:24 INFO]: 10 seconds left!
[14:52:29 INFO]: 5 seconds left!
[14:52:30 INFO]: 4 seconds left!
[14:52:31 INFO]: 3 seconds left!
[14:52:32 INFO]: 2 seconds left!
[14:52:33 INFO]: 1 second left!
[14:52:34 INFO]: Chests have been refilled!
[14:53:04 INFO]: Spawned 1Message not found(-137, 74, -285)!
[14:53:34 INFO]: Spawned 1Message not found(0, 73, -13)!
[14:54:04 INFO]: Spawned 1Message not found(-279, 54, 9)!
[14:54:34 INFO]: Spawned 1Message not found(-275, 57, -98)!
[14:55:04 INFO]: Spawned 1Message not found(236, 44, 96)!
[14:55:34 INFO]: Spawned 1Message not found(-137, 56, 180)!
[14:56:04 INFO]: Spawned 1Message not found(186, 74, -147)!
[14:56:34 INFO]: Spawned 1Message not found(154, 52, 122)!
[14:57:04 INFO]: Spawned 1Message not found(-124, 56, 100)!
[14:57:34 INFO]: Spawned 1Message not found(42, 51, -46)!
[14:58:04 INFO]: Spawned 1Message not found(9, 56, -103)!
[14:58:34 INFO]: Spawned 1Message not found(18, 65, 132)!
[14:59:04 INFO]: Spawned 1Message not found(-80, 55, 97)!

**Comment by Ayman-Isam** [comment] 2024-02-22 18:12
I was able to fix the no message found errors pretty easily, the error of not changing language is hard for me to replicate. I'm going to send you another version of this plugin but this time with more debug statements to your email. If the issue still persists, try sending me the server log file, if that doesn't work, send me the console copy.

**Comment by Ayman-Isam** [comment] 2024-02-22 18:24
On second thought, I'll upload it in the test branch again, check latest commit of test branch, it's called "hungergames latest.jar" in the target directory

**Comment by MyBlueHorizon** [comment] 2024-02-23 05:15
I don't find a files called hungergames latest.jar in target directory, but I find a jar called HungerGames-1.2.5-1.20.jar in the root of test branch. Log file is here.
[latest.log](https://github.com/Ayman-Isam/Hunger-Games/files/14381895/latest.log)

**Comment by Ayman-Isam** [comment] 2024-02-23 16:43
It seems that I made a mistake of forgetting to load the languageconfig in the /start method which is probably the reason you saw english text. I'm going to upload another verision to my test branch, the 1.20.4 is the updated one. Please let me know if you encounter any other issues.

**Comment by Ayman-Isam** [comment] 2024-02-23 16:52
For CI by Github Action, I've never used it before, but it's definetly something I can learn and implement so I'll do that too

**Comment by MyBlueHorizon** [comment] 2024-02-24 14:23
Form the information of the commit in test branch, the 1.20.4 is old file, but  HungerGames-1.2.5-1.20.jar is new, so I use it to test (on Paper 1.20.4).
Sadly, all of texts still in English, and "Message not found" still show on the "bossbar", but other place is right.
I change my client form Chinese to French, it still happen.
If everything work well in your side, I think maybe some strange thing happened when upload file to Github.

**Comment by Ayman-Isam** [comment] 2024-02-24 15:30
I think the problem is with the version of the plugin, I've deleted all the files there and there's currently just 2 files there, one original and one new one, please try the new version, if you still see the message not found then you're definitely using an older version of the plugin.

**Comment by MyBlueHorizon** [comment] 2024-02-25 06:24
Translation is working but sometings still in English(But have translation in lang file). 
![图片](https://github.com/Ayman-Isam/Hunger-Games/assets/20754543/ee3db75c-3ecd-4049-9694-a3e9af294a5f)
I think I can start to finish the change of Chinese lang file.

**Comment by Ayman-Isam** [comment] 2024-02-25 08:50
I'll look at the issues, I don't think I can translate the numbers however, since they're generated by the code, I can change the joined text however, as well as the game info text and the time remaining text. If you find any more english text, please let me know.

**Comment by Ayman-Isam** [comment] 2024-02-25 09:39
I've made some updates and it seems that the issue has been fixed in my device. Once again, I'm going to upload the latest version to the test branch, see if that works as intended.
![Screenshot 2024-02-25 113658](https://github.com/Ayman-Isam/Hunger-Games/assets/94015277/2b8c316d-cdfa-4607-aee6-c5d300a84bae)

**Comment by MyBlueHorizon** [comment] 2024-02-25 14:16
Seem here have file problems again. But all look like no problem from your picture. I want to start to update translation of chinese. If test branch have the latest text? If it has, I will upload new text soon.
[21:47:26 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'HungerGames-1.2.5-1.20.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.aymanisam.hungergames.HungerGames'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.4.jar:git-Paper-430]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.4.jar:git-Paper-430]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.4.jar:git-Paper-430]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-430]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-430]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-430]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.aymanisam.hungergames.HungerGames
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 10 more

**Comment by Ayman-Isam** [comment] 2024-02-25 14:44
Oops, I changed my plugin configurations and it seems to have broken the plugin, it should be fixed by now.

**Comment by MyBlueHorizon** [comment] 2024-02-26 04:14
Still happen.

**Comment by Ayman-Isam** [comment] 2024-02-26 05:14
I pushed another fix, this one should be it

**Comment by MyBlueHorizon** [comment] 2024-02-26 05:36
The latest commit is 14 hours ago. Maybe some error happened when you pushed.

**Comment by Ayman-Isam** [comment] 2024-02-26 05:57
Oops, I commited it in intellij but I forgot to push. I'm not at home but I'll try to push an update.

**Comment by Ayman-Isam** [comment] 2024-02-26 06:19
I've pushed an update but I don't really have a way right now to check it, can you let me know if it works?

**Comment by MyBlueHorizon** [comment] 2024-02-26 06:49
Working! But "Time remaining" and "Game Info" still in English.

**Comment by Ayman-Isam** [comment] 2024-02-26 10:25
That's nice to hear, lemme see what's wrong with time remaining and game info.

**Comment by Ayman-Isam** [comment] 2024-02-26 14:17
Ok I just pushed another version, this should be it! If you still have issues, please let me know.

**Comment by MyBlueHorizon** [comment] 2024-02-27 06:14
Time remaining working, but Game Info not working.
And I find a bug, if a player exit the game and there only one player still in game, although he will win, the boss bar still show.
And translation seem have some problem.
![图片](https://github.com/Ayman-Isam/Hunger-Games/assets/20754543/c73f6b9f-5d7a-4635-b482-6e59fa34d13a)

**Comment by Ayman-Isam** [comment] 2024-02-27 06:27
hmm I'll look into those

**Comment by Ayman-Isam** [comment] 2024-02-27 22:13
I have pushed an update, didn't have the chance to check if it works. Also I'll be on vacation for a few days so I might not be able to assist during that period.

**Comment by MyBlueHorizon** [comment] 2024-02-28 14:39
I can't find .jar file, so I can’t test it. But I finish improving Chinese translation, it can be merge. Also, my winter vacation will end, so I might not be able to test the change until weekend.

**Closed as completed** 2024-03-31 08:36 UTC
